site_name: LongPort OpenAPI SDK
docs_dir: docs

theme:
  name: readthedocs

nav:
  - Index: index.md
  - Code Reference:
      - All: reference_all.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_style: google
            show_source: false
            show_if_no_docstring: true
            members_order: source
            show_signature_annotations: true
            separate_signature: true
